# Generated by Django 2.2.19 on 2023-05-03 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Выберите изображение для поста', upload_to='posts/', verbose_name='Картинка'),
        ),
    ]
